import type { Metadata } from "next";
import BaseLayOutTemplate from "@/components/templetes/BaseLayOutTemplate";
import '../../public/style/nomalizeStyle.css'
import {inter} from "@/constant/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ko">
      <body className={inter.className}>
        <BaseLayOutTemplate>
            {children}
        </BaseLayOutTemplate>
      </body>
    </html>
  );
}
