import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
      <nav>
        <ul>
          <li>nav1</li>
        </ul>
      </nav>
      {children}
      <footer>
        <ol>THIS IS FOTTER</ol>
      </footer>
      </body>
    </html>
  );
}
